.TH "HUGO\-CHECK\-ULIMIT" "1" "Jul 2016" "Hugo 0.17-DEV" "Hugo Manual" 
.nh
.ad l


.SH NAME
.PP
hugo\-check\-ulimit \- Check system ulimit settings


.SH SYNOPSIS
.PP
\fBhugo check ulimit\fP


.SH DESCRIPTION
.PP
Hugo will inspect the current ulimit settings on the system.
This is primarily to ensure that Hugo can watch enough files on some OSs


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
    config file (default is path/config.yaml|json|toml)

.PP
\fB\-\-log\fP[=false]
    Enable Logging

.PP
\fB\-\-logFile\fP=""
    Log File path (if set, logging enabled automatically)

.PP
\fB\-v\fP, \fB\-\-verbose\fP[=false]
    verbose output

.PP
\fB\-\-verboseLog\fP[=false]
    verbose logging


.SH SEE ALSO
.PP
\fBhugo\-check(1)\fP
