baseurl = "http://blog.nickklauer.info/"
languageCode = "en-us"
title = "I'd like to say I'm militant about it, but that's kind of who I am"
pygmentsuseclasses="false"
pygmentsstyle = "native"

[params]
copyright = "2016 Nick Klauer"
logo = "https://s.gravatar.com/avatar/76c55292df5e9df9042eaf89ac35954b?s=80"
