baseurl = "https://blog.nickklauer.info/"
languageCode = "en-us"
pygmentsstyle = "native"
pygmentsuseclasses = false
pygmentsCodeFences = true
theme = "hugo-zen"
title = "A Blog"

[params]
  copyright = "2012 - 2018 Nick Klauer"
  logo = "https://s.gravatar.com/avatar/76c55292df5e9df9042eaf89ac35954b?s=80"

